DROP TABLE IF EXISTS AUTHORS;
DROP TABLE IF EXISTS BOOKS;
DROP TABLE IF EXISTS GENERIS;


CREATE TABLE GENERIS(ID BIGINT PRIMARY KEY, NAME VARCHAR(255));
CREATE TABLE AUTHORS(ID BIGINT PRIMARY KEY, NAME VARCHAR(255), SURNAME VARCHAR(255), MIDDLENAME VARCHAR(255));
CREATE TABLE BOOKS(ID BIGINT PRIMARY KEY, NAME VARCHAR(255),  GENRE_ID BIGINT, AUTHOR_ID BIGINT);


ALTER TABLE BOOKS ADD FOREIGN KEY (GENRE_ID) REFERENCES GENERIS(ID);
ALTER TABLE BOOKS ADD FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHORS(ID);
