spring:
  datasource:
    url: jdbc:h2:mem:test
    initialization-mode: always
  h2:
    console.enabled: true

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: health, logfile, metrics, prometheus
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled: true

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  level:
    ROOT: info
  file:
    name: logs/logfile.log
